### ISSUE TITLE
Error associating lambda function

### ISSUE THREAD

**Issue by MrStiMu** [sanfrancesco/prerendercloud-lambda-edge#1]
Hello,

This is the message i see after using make deploy:

------Error while associating Lambda functions with CloudFront------

```
{ InvalidLambdaFunctionAssociation: The function code size is larger than the maximum allowed size for functions that are triggered by a CloudFront event: 13810013 Max allowed: 1048576 Function: arn:aws:lambda:us-east-1:934024889921:function:Lambda-Edge-Prerendercloud-dev-viewerRequest:1
    at Request.extractError (/Users/sjdmulde/Projects/prerendercloud-lambda-edge/node_modules/aws-sdk/lib/protocol/rest_xml.js:53:29)
    at Request.callListeners (/Users/sjdmulde/Projects/prerendercloud-lambda-edge/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/sjdmulde/Projects/prerendercloud-lambda-edge/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/sjdmulde/Projects/prerendercloud-lambda-edge/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/sjdmulde/Projects/prerendercloud-lambda-edge/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/sjdmulde/Projects/prerendercloud-lambda-edge/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/sjdmulde/Projects/prerendercloud-lambda-edge/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/sjdmulde/Projects/prerendercloud-lambda-edge/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/sjdmulde/Projects/prerendercloud-lambda-edge/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/sjdmulde/Projects/prerendercloud-lambda-edge/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'The function code size is larger than the maximum allowed size for functions that are triggered by a CloudFront event: 13810013 Max allowed: 1048576 Function: arn:aws:lambda:us-east-1:934024889921:function:Lambda-Edge-Prerendercloud-dev-viewerRequest:1',
  code: 'InvalidLambdaFunctionAssociation',
  time: 2017-09-23T17:50:19.646Z,
  requestId: 'a7d93ab3-a087-11e7-b1ad-0b8d548a9b8a',
  statusCode: 400,
  retryable: false,
  retryDelay: 17.514498835987812 }
```

**Comment by MrStiMu** [comment]
yarn on macOs

**Comment by MrStiMu** [comment]
This is the full output:

MacBook-Pro-van-Stijn:prerendercloud-lambda-edge sjdmulde$ make deploy
yarn run serverless -- deploy
yarn run v1.0.2
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ "/Users/sjdmulde/Projects/prerendercloud-lambda-edge/node_modules/.bin/serverless" "deploy"
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (13.17 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
........................
Serverless: Stack update finished...
Service Information
service: Lambda-Edge-Prerendercloud
stage: dev
region: us-east-1
api keys:
  None
endpoints:
  None
functions:
  viewerRequest: Lambda-Edge-Prerendercloud-dev-viewerRequest
  originRequest: Lambda-Edge-Prerendercloud-dev-originRequest
✨  Done in 51.93s.
node deploy.js
before []
after [ { EventType: 'viewer-request',
    LambdaFunctionARN: 'arn:aws:lambda:us-east-1:934024889921:function:Lambda-Edge-Prerendercloud-dev-viewerRequest:1' },
  { EventType: 'origin-request',
    LambdaFunctionARN: 'arn:aws:lambda:us-east-1:934024889921:function:Lambda-Edge-Prerendercloud-dev-originRequest:1' } ]


------Error while associating Lambda functions with CloudFront------


{ InvalidLambdaFunctionAssociation: The function code size is larger than the maximum allowed size for functions that are triggered by a CloudFront event: 13810013 Max allowed: 1048576 Function: arn:aws:lambda:us-east-1:934024889921:function:Lambda-Edge-Prerendercloud-dev-viewerRequest:1
    at Request.extractError (/Users/sjdmulde/Projects/prerendercloud-lambda-edge/node_modules/aws-sdk/lib/protocol/rest_xml.js:53:29)
    at Request.callListeners (/Users/sjdmulde/Projects/prerendercloud-lambda-edge/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/sjdmulde/Projects/prerendercloud-lambda-edge/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/sjdmulde/Projects/prerendercloud-lambda-edge/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/sjdmulde/Projects/prerendercloud-lambda-edge/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/sjdmulde/Projects/prerendercloud-lambda-edge/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/sjdmulde/Projects/prerendercloud-lambda-edge/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/sjdmulde/Projects/prerendercloud-lambda-edge/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/sjdmulde/Projects/prerendercloud-lambda-edge/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/sjdmulde/Projects/prerendercloud-lambda-edge/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'The function code size is larger than the maximum allowed size for functions that are triggered by a CloudFront event: 13810013 Max allowed: 1048576 Function: arn:aws:lambda:us-east-1:934024889921:function:Lambda-Edge-Prerendercloud-dev-viewerRequest:1',
  code: 'InvalidLambdaFunctionAssociation',
  time: 2017-09-23T17:50:19.646Z,
  requestId: 'a7d93ab3-a087-11e7-b1ad-0b8d548a9b8a',
  statusCode: 400,
  retryable: false,
  retryDelay: 17.514498835987812 }








Successfully associated Lambda functions with CloudFront


node create-invalidation.js
{ Location: 'https://cloudfront.amazonaws.com/2017-03-25/distribution/E3OI5WRANYZX2V/invalidation/I2ZLMMP6HUJ5V2',
  Invalidation: 
   { Id: 'I2ZLMMP6HUJ5V2',
     Status: 'InProgress',
     CreateTime: 2017-09-23T17:50:16.470Z,
     InvalidationBatch: { Paths: [Object], CallerReference: '2017-09-23T17:50:19.857Z' } } }

**Comment by jotto** [comment]
Can you also verify whether you have a `package-lock.json` in your dir?

**Comment by MrStiMu** [comment]
No i don't

**Comment by MrStiMu** [comment]
i have a yarn.lock

**Comment by jotto** [comment]
also print a listing of your node_modules

`ls node_modules`

**Comment by MrStiMu** [comment]
![image](https://user-images.githubusercontent.com/24266455/30775786-0bef3e74-a09b-11e7-9904-36fdcac05050.png)

**Comment by MrStiMu** [comment]
Should i do an npm install?

**Comment by jotto** [comment]
no, do not do `npm install`, that will create the package-lock.json which I know causes problems for serverless.

Run this: `grep version node_modules/serverless/package.json`

**Comment by MrStiMu** [comment]
"version": "1.19.0",

**Comment by jotto** [comment]
OK - I am finally able to reproduce this on my end, investigating now.

**Comment by MrStiMu** [comment]
Ok thank you

**Comment by MrStiMu** [comment]
The inital yarn command was with yarn version 0.23 and afterwards i did an upgrade before running the make deploy.

Full output:

MacBook-Pro-van-Stijn:prerendercloud-lambda-edge sjdmulde$ yarn
yarn install v0.23.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
warning Your current version of Yarn is out of date. The latest version is "1.0.2" while you're on "0.23.2".

**Comment by jotto** [comment]
OK - looks like there might be an issue with the latest version of yarn and serverless for excluding dev dependencies in the production bundle.

So ignore my previous comment about `package-lock.json`, apparently that's now required for serverless to work.

`npm install` should solve the issue. I'll update the docs

**Comment by MrStiMu** [comment]
Ok, i've executed npm install (had to re-install npm because of a homebrew problem) and now i get:

MacBook-Pro-van-Stijn:prerendercloud-lambda-edge sjdmulde$ make deploy
yarn run serverless -- deploy
yarn run v1.0.2
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ "/Users/sjdmulde/Projects/prerendercloud-lambda-edge/node_modules/.bin/serverless" "deploy"
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (288.18 KB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.....
Serverless: Operation failed!
 
  Serverless Error ---------------------------------------
 
  An error occurred: ViewerRequestLambdaFunction - Function not found: arn:aws:lambda:us-east-1:934024889921:function:Lambda-Edge-Prerendercloud-dev-viewerRequest.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.5.0
     Serverless Version:     1.23.0
 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [deploy] Error 1

**Comment by jotto** [comment]
`git pull && rm -rf node_modules`

**Comment by jotto** [comment]
`git pull && rm -rf node_modules && npm install`

**Comment by MrStiMu** [comment]
After doing a git pull

MacBook-Pro-van-Stijn:prerendercloud-lambda-edge sjdmulde$ git pull
Already up-to-date.
MacBook-Pro-van-Stijn:prerendercloud-lambda-edge sjdmulde$ rm -rf node_modules
MacBook-Pro-van-Stijn:prerendercloud-lambda-edge sjdmulde$ npm install

> spawn-sync@1.0.15 postinstall /Users/sjdmulde/Projects/prerendercloud-lambda-edge/node_modules/spawn-sync
> node postinstall


> serverless@1.23.0 postinstall /Users/sjdmulde/Projects/prerendercloud-lambda-edge/node_modules/serverless
> node ./scripts/postinstall.js

npm WARN prerendercloud-lambda-edge No repository field.
npm WARN prerendercloud-lambda-edge No license field.

added 274 packages in 5.409s
MacBook-Pro-van-Stijn:prerendercloud-lambda-edge sjdmulde$ make deploy
./node_modules/.bin/serverless deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (257.11 KB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.....
Serverless: Operation failed!
 
  Serverless Error ---------------------------------------
 
  An error occurred: ViewerRequestLambdaFunction - Function not found: arn:aws:lambda:us-east-1:934024889921:function:Lambda-Edge-Prerendercloud-dev-viewerRequest.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.5.0
     Serverless Version:     1.23.0
 
make: *** [deploy] Error 1

**Comment by jotto** [comment]
Delete your .serverless dir and/or the function in lambda and do it again

**Comment by MrStiMu** [comment]
I've deleted the AWS resources (S3 bucket, functions and cloudformation stack).

When i execute the code i get a deployment:

MacBook-Pro-van-Stijn:prerendercloud-lambda-edge sjdmulde$ make deploy
./node_modules/.bin/serverless deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
.....
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (256.3 KB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
........................
Serverless: Stack update finished...
Service Information
service: Lambda-Edge-Prerendercloud
stage: dev
region: us-east-1
stack: Lambda-Edge-Prerendercloud-dev
api keys:
  None
endpoints:
  None
functions:
  viewerRequest: Lambda-Edge-Prerendercloud-dev-viewerRequest
  originRequest: Lambda-Edge-Prerendercloud-dev-originRequest


BUT when i goto the functions in AWS (Lambda functions), there is no associated trigger with cloudfront. I am now manually adding the trigger and see what happens

**Comment by jotto** [comment]
I haven't seen in the Lambda UI after running this deployment script (specifically the API calls for associating the Lambda function with the distribution) - I believe it's a bug somewhere in the AWS console. But I always see it at the bottom of the "Behaviors" tab for the CloudFront Distribution.

**Comment by jotto** [comment]
![image](https://user-images.githubusercontent.com/16573/30780051-b2046350-a0b6-11e7-9ff8-edd199e15562.png)

You should see requests after logging into prerender.cloud and more importantly, you should see logs in AWS CloudWatch in one of the regions you are closest to geographically. For example, I am in San Francisco and I see CloudWatch logs in us-west-2 Oregon (it should be in us-west-1 N California for me but it's not perfect).

**Comment by MrStiMu** [comment]
I managed to get it working, but now i get errors in:

![image](https://user-images.githubusercontent.com/24266455/30781088-2a0eb1e0-a119-11e7-96f6-844890d78e5d.png)

There is no explanation in cloudwatch why it's giving errros.

**Comment by jotto** [comment]
The issues here are resolved because:

* a yarn bug was fixed
* instructions in the README have been revised to simplify setup - and point out that you must crawl the URLs to get them cached in service.prerender.cloud, otherwise they will timeout)

For posterity, it seems as of Nov 2017 you can't delete Lambda@Edge functions, so if you ever attempt to delete them, it will time out or fail. If, at that point you want to re-use this project, you'll have to rename the functions (in about 2 places)
