### ISSUE TITLE
what if i over write content of my bucket.

### ISSUE THREAD

**Issue by matesio** [sanfrancesco/prerendercloud-lambda-edge#12]
Hi, i know this can not be an issue, i am just trying to figure out, what if i delete whole content of my bucket after deployment of prerendercloud-lambda-edge , should i need to deploy it again?

**Comment by jotto** [comment]
Yes you will need to deploy the content to s3 again.

There's a chance things will still work from some of CloudFront's network, but as far as I know they have hundreds of PoPs (nodes) each with their own cache. So if any of those uncached nodes are hit, and the s3 content is gone, then the request will fail.

**Comment by matesio** [comment]
I am deploying my apllication from github to s3 with versioning enabled, how should i deploy lambda@edge in this case.

**Comment by jotto** [comment]
Sorry for the delay.

S3 with versioning should not change anything. Proceed as normal
