### ISSUE TITLE
Question: Do you use this for subsequent deploys?

### ISSUE THREAD

**Issue by kjanoudi** [sanfrancesco/prerendercloud-lambda-edge#2]
If i have a code change, should i be using this script to deploy my new code every time, or can i simply invalidate in cloudfront as i used to do before adding the lambda@edge functions using this repo? Will the prerendered versions pick up on the invalidation and automatically re-fetch on the next request, or will prerender be out of sync with my cloudfront?

**Comment by jotto** [comment]
> should i be using this script to deploy my new code every time

No. If you change your website (html or JavaScript), you should only have to invalidate CloudFront.

I should clarify that in the docs.

**Caveat:** By default, Prerender.cloud will cache on its servers for 5 minutes, so it's possible prerender.cloud will return out-dated cache after you invalidate CloudFront.

You can disable the server cache with: `prerendercloud.set('disableServerCache', true);` (edit `handler.js` and re-deploy the Lambda@Edge function).

I also, still, need to create an API method still for invalidating the entire cache on prerender.cloud's servers.

**Comment by kjanoudi** [comment]
Thanks!
