### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by georgeboot** [sanfrancesco/prerendercloud-lambda-edge#22]
This package is using some older dependencies:

### Node.js 8.x
Note that Node.js 8.x will de EOL on December 31, 2019
https://github.com/sanfrancesco/prerendercloud-lambda-edge/blob/606976fb6da039edd6374797cd6d13630882c961/serverless.yml#L12

### Serverless Framework 1.38
The most current version is 1.57. The version currently being used was released on February 20, 2019. This is 9 months ago.
https://github.com/sanfrancesco/prerendercloud-lambda-edge/blob/606976fb6da039edd6374797cd6d13630882c961/package.json#L6

**Comment by jotto** [comment]
Thank you for the clearly written issue, will do.

The runtime is easy (simply change it to the latest version https://github.com/sanfrancesco/prerendercloud-lambda-edge/blob/606976fb6da039edd6374797cd6d13630882c961/serverless.yml#L12) and re-deploy.

I need to do some testing with the latest version of serverless.
